minimumReleaseAgeExclude:
  - '@deepseek-ai/dsh-api-session-controller@0.2.1-alpha.1'
  - '@deepseek-ai/dsh-client-locale@0.2.1-alpha.1'
  - '@deepseek-ai/dsh-client-store@0.2.1-alpha.1'
  - '@deepseek-ai/dsh-client-ui-conversation@0.2.1-alpha.1'
  - '@deepseek-ai/dsh-client-ui-primitives@0.2.1-alpha.1'
  - '@deepseek-ai/dsh-client-ui-renderer@0.2.1-alpha.1'
  - '@deepseek-ai/dsh-client-ui-session@0.2.1-alpha.1'
  - '@deepseek-ai/dsh-client-ui-slots@0.2.1-alpha.1'
